# Generated by Django 4.2.9 on 2024-07-20 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tests',
        ),
    ]
