# Generated by Django 4.2.9 on 2024-07-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0002_alter_test_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
