# Generated by Django 4.2.9 on 2024-07-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests_app', '0003_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('test1', models.TextField()),
                ('test2', models.TextField()),
                ('test3', models.TextField()),
                ('test4', models.TextField()),
                ('test5', models.TextField()),
            ],
        ),
    ]
