# Generated by Django 4.2.9 on 2024-07-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='test1',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tests',
            name='test2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tests',
            name='test3',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tests',
            name='test4',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tests',
            name='test5',
            field=models.TextField(default=''),
        ),
    ]
