# Generated by Django 4.2.9 on 2024-07-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0007_rename_test1_tests_result_rename_test2_tests_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='test',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tests',
            name='user',
            field=models.TextField(default=''),
        ),
    ]
